#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-simpleframework
Version  : 1
Release  : 1
URL      : https://repo.gradle.org/gradle/libs-releases/org/simpleframework/simple/4.1.21/simple-4.1.21.jar
Source0  : https://repo.gradle.org/gradle/libs-releases/org/simpleframework/simple/4.1.21/simple-4.1.21.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/org/simpleframework/simple/4.1.21/simple-4.1.21.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-simpleframework-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-simpleframework package.
Group: Data

%description data
data components for the mvn-simpleframework package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/simpleframework/simple/4.1.21
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/simpleframework/simple/4.1.21/simple-4.1.21.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/simpleframework/simple/4.1.21
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/simpleframework/simple/4.1.21/simple-4.1.21.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/simpleframework/simple/4.1.21/simple-4.1.21.jar
/usr/share/java/.m2/repository/org/simpleframework/simple/4.1.21/simple-4.1.21.pom
